// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZIa5kFlPSbPJhaSMmRtNDqoHiuRX1Sbo',
    appId: '1:855722263186:web:41803f1b5b973605dd5c4b',
    messagingSenderId: '855722263186',
    projectId: 'study-app-tut',
    authDomain: 'study-app-tut.firebaseapp.com',
    storageBucket: 'study-app-tut.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_-fkS33ge1vo2BGX3_pVwHd4XMbwNM6A',
    appId: '1:855722263186:android:5ff98ff90543c357dd5c4b',
    messagingSenderId: '855722263186',
    projectId: 'study-app-tut',
    storageBucket: 'study-app-tut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhyaQUY_i-DShD9DzvaPN6dxNeNjfeVAA',
    appId: '1:855722263186:ios:128902799335ce09dd5c4b',
    messagingSenderId: '855722263186',
    projectId: 'study-app-tut',
    storageBucket: 'study-app-tut.appspot.com',
    iosClientId: '855722263186-jlo6t7ipg2spe844im08mc3d8b4lqdhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhyaQUY_i-DShD9DzvaPN6dxNeNjfeVAA',
    appId: '1:855722263186:ios:1d539266a8320002dd5c4b',
    messagingSenderId: '855722263186',
    projectId: 'study-app-tut',
    storageBucket: 'study-app-tut.appspot.com',
    iosClientId: '855722263186-v4qpnoi6f60003qoef0uknpuoovcuhai.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp.RunnerTests',
  );
}
